### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#1]
As a website user, I can log in from the main page using my credentials so that I can create an order or see status of my previous orders 

## Acceptance Criteria: 

-  When logged out, the user can see and click on a 'login' button 
- After clicking on login button, user is redirected to main page and logged in
- The personal area should now not accessible

## Tasks:

- [x]  (backend / BE) Implement Login functionality on server side
- [x] (frontend / FE) Add Login buttons to page/navbar and add event listener 
- [x]  (frontend) Visual Feedback (such as message or modal) that login was successful
