### ISSUE TITLE
USER STORY: Add Product to Shopping Bag

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#23]
As a website user, I can add products to my shopping bag so that I can keep looking for more products before I checkout and pay 

## Acceptance Criteria: 

- when clicking on a product detail page on the `add to shopping bag` button, a visual feedback i.e. a toast appears that adding was successful 
- In addition, the added item should be in the preview of the shopping bag and in the detailed view of the shopping bag 
- The grand total needs to be correctly updated when adding an item 
- The shopping bag remains unchanged when the user keeps shopping 

## Tasks:

- [x] (FE) create UI elements such as ‘add’ buttons on detail form and on the shop list view 
- [x] (FE) add forms for adding products to bag to UI layout 
- [x] (FE) add visual feedback i.e. in form of toast after successful adding to shopping bag
- [x] (BE) design DB relationships for creating an order 
- [x] (BE) add shopping bag app
- [x] (BE) Add models for Order and OrderLineItems
- [x] -  (BE) add shopping bag context processor 
- [x] (BE) add URLs and views for adding items to shopping bag
