### ISSUE TITLE
USER STORY: Update Shopping Bag

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#24]
As a website user, I can click on interactive elements such as buttons next to bag items so that I can edit the quantity of items in my shopping bag

## Acceptance Criteria: 
 
- [ ] when the user clicks on the  ‘+’ or “-” buttons, the quantity on product detail form and on the preview changes 
- [ ] When the user presses the ‘save changes’ button, the updated quantities are stored 
- [ ] When the user presses the ‘cancel’ button, the new quantities are discarded and the previous quantities are loaded  

## Tasks:

- [x] (FE) create UI elements such as ‘+’ or “-” buttons or buttons to change quantity on product detail form and on the preview
- [x] (FE) create UI element such as buttons to ‘confirm’ or ‘cancel’ the operation of changing quantities of the shopping bag  
- [x] (FE) add visual feedback i.e. in form of toast after successful changing the quantity 
- [x] (BE) add URLs, forms and views to for changing the quantities
