### ISSUE TITLE
USER STORY: Purchase Items

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#26]
As a website user, I can purchase products in my shopping bag using a secure system so that I can place an order for the product in exchange for money  

## Acceptance Criteria: 

- [ ] when the user provides valid credit card information (or the Stripe test card information) the order should be placed when the user clicks on ‘confirm purchase’ button on checkout page
- [ ] In the admin panel, the new order can be found with the correct details 
- [ ] On Stripe Dashboard, a record of the purchase can be found 
- [ ] A toast appears if purchase was successful, or a warning toast appears if not containing the error message

## Tasks:

- [x] (FE) create UI elements such as a form and submit buttons that contain enough information to place a purchase with Stripe 
- [x] (FE) create UI element for the order summary for the checkout page 
- [x] (FE) add visual feedback i.e. in form of toast after successful or failed purchase intent 
- [x] (BE) add URLs, forms and views to render the checkout page when the user clicks on UI element to confirm purchase, i.e. a ’secure payment’ button 
- [x] (BE) create web hooks that process the communication with Stripe account associated with the page
- [x] (BE) create web hooks handler that is called after a successful purchase, i.e. to enter the order in the DB purchase history of the user 
- [x] (BE) create web hooks handler that is called after the purchase failed
