### ISSUE TITLE
USER STORY: Overview of Products in the Shop

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#33]
As a website user, I can enter the main page of the shop so that I can see all the products available in the shop

## Acceptance Criteria: 

- when visiting the page, the user should be directed to this page 
- All products should be listed here and the user can scroll through the items 
- 

## Tasks:

- [x] (FE) create UI for shop including a list view of all the products in the shop  
- [x] (FE) update links on in navbar with the shop page 
- [x] (FE)  add landing page including at least one CTA 
- [x] (BE) create URL and view for the shop page
