### ISSUE TITLE
USER STORY: Order By Price

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#35]
As a website user, I can sort the product list by Price so that I can find the cheapest option available for the current category

## Acceptance Criteria: 

when clicking on the ‘filter by Category’ item, the items are sorted by price
For both ascending and descending order 

## Tasks:

- [x] (FE) create UI elements for ‘sort by’ selection box on the product detail page 
- [x] (FE) add implement the sorting functionality by Price to hide elements, for example using Javascript
- [x] (FE) Implement both for  descending and ascending order
