### ISSUE TITLE
USER STORY: Rate Product

### ISSUE THREAD

**Issue by nils-n** [nils-n/cycle-to-work#49]
As an authenticated website user, I can rate my previous orders so that I can express my opinion about a product to other users 

## Acceptance Criteria: 

- each rating has an ‘give rating’ button attached
- After clicking on ‘gif rating’ button, an interactive field such as slider or option to click on the rating stars appears and the use can change it 
- after clicking on button to save changes, the rating is saved
- The overall product rating is updated accordingly as average of all ratings 

## Tasks:

- [ ] (frontend) create UI elements such as buttons and interactive icons such as stars,)and design their layout on the page
- [ ] (backend) add view functions to enter ratings into DB  
- [ ] (backend) create data structure for comments to reflect feature
